it('Add article', () => {
  cy.visit('/login');
  let articleTitle = "Test";
  cy.url().should('include', '/login');
  cy.get('.form.nickname input').clear().type('admin');
  cy.get('.form.password input').clear().type('admincool');
  cy.get('.content .enter').click();
  cy.url().should('not.include', 'login');
  cy.url().should('include', '/');
  cy.get('poly-header .actions a:nth-child(2)').click();
  cy.url().should('include', '/upload');
  cy.get('.form div:first-child .select .block:nth-child(3)').click();
  cy.get('.form div:nth-child(2) .select .block:nth-child(3)').click();
  cy.get('.name-input').clear().type(articleTitle);
  let preview = (Math.random() + 1).toString(36).substring(7);
  let text = (Math.random() + 1).toString(36).substring(7);
  let firstTag = (Math.random() + 1).toString(36).substring(7);
  let secondTag = (Math.random() + 1).toString(36).substring(7);
  let tags = firstTag + "," + secondTag;
  cy.get('.preview-input').clear().type(preview);
  cy.get('.text-input').clear().type(text);
  cy.get('.tags-input').clear().type(tags);
  cy.get('.content > button').click();
  cy.url().should('not.include', '/upload');
  cy.get('h2.title').should('have.text', articleTitle);
  cy.get('article > .body').should('have.text', text);
  cy.get('.tags.actual a:nth-child(1)').should('have.text', firstTag);
  cy.get('.tags.actual a:nth-child(2)').should('have.text', secondTag);
  let comment = (Math.random() + 1).toString(36).substring(7);
  cy.get('.comment-input textarea').clear().type(comment);
  cy.get('.comment-input button').click();
  cy.get('poly-comment:first-child .text').should("have.text", comment);
});
