# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

concurrency:
  group: ci-${{ github.ref }}-group
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup DB
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12'
          postgresql db: postgres
          postgresql user: postgres
          postgresql password: postgres

      - name: Pull repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run build
        run: mvn -Dmaven.test.skip=true install --file backend/pom.xml

      - name: Run Unit Test
        run: mvn surefire:test --file backend/pom.xml

      - name: Run Integration Test
        run: mvn failsafe:integration-test --file backend/pom.xml